name: Deploy .NET to AWS EC2

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.200" # Match your project version

            - name: Publish app
              run: dotnet publish -c Release -o publish

            - name: Upload to EC2 via SCP
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ 13.204.67.206 }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  source: "publish/*"
                  target: "/home/ubuntu/whole_crm"

            - name: Restart systemd service
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      sudo systemctl restart kestrel-whole-crm.service
